# Nombre interno de la aplicacion
spring.application.name=donde-entreno-api

# Puerto donde va a levantar el backend
server.port=${PORT:8080}

# Perfil activo por defecto para desarrollo local
spring.profiles.active=local

# ===============================
# CONFIGURACION DE JPA / HIBERNATE
# ===============================

# Le decimos a Hibernate que NO cree, modifique ni borre tablas.
# Como vos ya creaste la base con scripts SQL, esto es importante.
spring.jpa.hibernate.ddl-auto=none

# Muestra en consola las consultas SQL que ejecute JPA.
# Mas adelante podemos apagarlo.
spring.jpa.show-sql=true

# Formatea las consultas SQL para que sean mas legibles en consola.
spring.jpa.properties.hibernate.format_sql=true

# Dialecto especifico para PostgreSQL.
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Origenes permitidos por CORS
app.cors.allowed-origins=http://localhost:3000